/**
 * Regenerate convex/phiConsoleStatics.ts — the allowlist of console
 * messages that survive PHI redaction (see convex/phiLogging.ts).
 *
 * Collects the first argument of every console call in convex/ source when
 * it is a string literal or a substitution-free template literal. Those are
 * compile-time constants of the code and can never carry PHI, so they stay
 * readable in Convex logs on PHI deployments; everything else is redacted
 * at runtime. The Viktor platform runs this script against the exact source
 * being deployed, before every PHI deploy.
 *
 * Usage: bun run --bun scripts/generate-phi-console-statics.ts
 */
import { readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
// The project's `typescript` is the native compiler (7.x), which ships no
// parser API; `typescript-api` is the JS-based TypeScript kept for it.
import ts from "typescript-api";

const CONSOLE_METHODS = new Set([
  "debug",
  "log",
  "info",
  "warn",
  "error",
  "trace",
  "time",
  "timeEnd",
  "timeLog",
]);

const STATICS_FILENAME = "phiConsoleStatics.ts";

export function extractConsoleStaticMessages(
  sourceText: string,
  fileName = "source.ts",
): string[] {
  const source = ts.createSourceFile(
    fileName,
    sourceText,
    ts.ScriptTarget.Latest,
    /* setParentNodes */ true,
    fileName.endsWith(".tsx") ? ts.ScriptKind.TSX : ts.ScriptKind.TS,
  );
  const messages: string[] = [];
  const visit = (node: ts.Node): void => {
    if (
      ts.isCallExpression(node) &&
      ts.isPropertyAccessExpression(node.expression) &&
      ts.isIdentifier(node.expression.expression) &&
      node.expression.expression.text === "console" &&
      CONSOLE_METHODS.has(node.expression.name.text) &&
      node.arguments.length > 0
    ) {
      const first = node.arguments[0];
      if (
        ts.isStringLiteral(first) ||
        ts.isNoSubstitutionTemplateLiteral(first)
      ) {
        messages.push(first.text);
      }
    }
    ts.forEachChild(node, visit);
  };
  visit(source);
  return messages;
}

export function collectConvexSourceFiles(convexDir: string): string[] {
  const files: string[] = [];
  const walk = (dir: string): void => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (entry.name === "_generated") continue;
      const path = join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(path);
        continue;
      }
      if (entry.name === STATICS_FILENAME) continue;
      if (entry.name.endsWith(".ts") || entry.name.endsWith(".tsx")) {
        files.push(path);
      }
    }
  };
  walk(convexDir);
  return files.sort();
}

export function renderStaticsModule(messages: string[]): string {
  const unique = [...new Set(messages)].sort();
  const entries = unique
    .map(message => `  ${JSON.stringify(message)},`)
    .join("\n");
  const body =
    unique.length === 0
      ? "export const PHI_CONSOLE_STATIC_MESSAGES: string[] = [];"
      : `export const PHI_CONSOLE_STATIC_MESSAGES: string[] = [\n${entries}\n];`;
  return `// Generated by scripts/generate-phi-console-statics.ts — do not edit by hand.
//
// String literals used in console calls in this project's convex/ source.
// On PHI deployments (VIKTOR_SPACES_PHI_MODE=true) only these compile-time
// constants survive console redaction; every other message is replaced with
// the ***PHI_REDACTED*** sentinel (see phiLogging.ts). The Viktor platform
// regenerates this file from the deployed source before every PHI deploy.
${body}
`;
}

async function main(): Promise<void> {
  const projectRoot = dirname(import.meta.dir);
  const convexDir = join(projectRoot, "convex");
  const files = collectConvexSourceFiles(convexDir);
  const messages: string[] = [];
  for (const file of files) {
    const text = await Bun.file(file).text();
    messages.push(...extractConsoleStaticMessages(text, file));
  }
  const outPath = join(convexDir, STATICS_FILENAME);
  writeFileSync(outPath, renderStaticsModule(messages));
  console.log(
    `Wrote ${new Set(messages).size} static console message(s) from ` +
      `${files.length} file(s) to ${outPath}`,
  );
}

if (import.meta.main) {
  await main();
}
