import { Link } from "react-router";
import archLayers from "./assets/arch-layers.svg";
import archTiers from "./assets/arch-tiers.svg";

function Window({ title, children, className = "" }: { title: string; children: React.ReactNode; className?: string }) {
  return (
    <div className={`flex flex-col overflow-hidden rounded-lg border border-border bg-card shadow-[0_30px_60px_-30px_color-mix(in_oklab,var(--ink)_35%,transparent)] ${className}`}>
      <div className="flex items-center gap-2 border-b border-border px-4 py-3">
        <span className="h-2.5 w-2.5 rounded-full bg-border" />
        <span className="h-2.5 w-2.5 rounded-full bg-border" />
        <span className="h-2.5 w-2.5 rounded-full bg-border" />
        <span className="ml-3 text-xs font-medium uppercase tracking-widest text-muted-foreground">{title}</span>
      </div>
      <div className="flex-1 p-6">{children}</div>
    </div>
  );
}

export function PlatformPreview() {
  return (
    <section className="border-t border-border bg-secondary/50">
      <div className="reveal mx-auto max-w-6xl px-6 py-28">
        <p className="eyebrow text-accent">What members get</p>
        <h2 className="mt-4 max-w-3xl text-4xl leading-tight md:text-5xl">A shared library, an AI that reads it, and architecture diagrams that evolve with it.</h2>

        <div className="mt-16 grid gap-6 lg:grid-cols-2">
          <Link to="/submit" className="flex transition-opacity hover:opacity-90"><Window title="Contribute" className="w-full">
            <div className="grid h-full place-items-center rounded-md border-2 border-dashed border-border bg-background px-6 py-10 text-center">
              <div>
                <p className="text-2xl font-semibold tracking-tight">Drop a non-confidential document</p>
                <p className="mt-2 text-sm text-muted-foreground">Diagrams, due diligence, privacy and security assessments, board materials.</p>
                <div className="mt-6 inline-flex items-center gap-2 rounded-full border border-border px-3 py-1 text-xs text-muted-foreground">
                  <span className="h-1.5 w-1.5 rounded-full bg-accent" /> Screened by AI before anything is published
                </div>
              </div>
            </div>
          </Window></Link>

          <Link to="/ask" className="flex transition-opacity hover:opacity-90"><Window title="Ask the library" className="w-full">
            <div className="space-y-4 text-sm">
              <div className="ml-auto max-w-[85%] rounded-lg bg-primary px-4 py-3 text-primary-foreground">
                Where do most members place a human in the loop for distribution decisions?
              </div>
              <div className="max-w-[92%] leading-relaxed">
                Most contributed designs require a named person to decide any distribution, with the AI limited to assembling the file and citing its sources. Two contributions suggest a lighter review for routine, rules-based payments.
                <div className="mt-3 flex flex-wrap gap-2">
                  {["Reference architecture v4", "Board ratification memo", "Review tiers note"].map((s) => (
                    <span key={s} className="rounded-sm border border-border bg-background px-2 py-0.5 text-xs text-muted-foreground">{s}</span>
                  ))}
                </div>
              </div>
              <div className="flex items-center gap-2 rounded-md border border-border bg-background px-3 py-2.5 text-muted-foreground">
                <span className="flex-1">Ask about shared, non-confidential material…</span>
                <span className="rounded-sm bg-primary px-2 py-1 text-xs text-primary-foreground">Ask</span>
              </div>
            </div>
          </Window></Link>

          <Window title="Suggested reference architecture" className="lg:col-span-2">
            <p className="max-w-2xl text-sm text-muted-foreground">Generated by AI from the library. Shows where members agree and where alternatives exist. Updates as the library grows. Suggestions only, not a standard.</p>
            <div className="mt-8 rounded-lg bg-secondary/60 p-6 md:p-10">
              <p className="eyebrow text-accent">Five layers, every deployment</p>
              <img src={archLayers} alt="Reference architecture: staff and identity provider, the firm's own tenant with web app, gateway, orchestration, model, secrets, audit trail and scheduler, human review, a named cross-region exception, and read-only systems of record." className="mt-6 w-full" />
            </div>
            <div className="mt-6 rounded-lg bg-secondary/60 p-6 md:p-10">
              <p className="eyebrow text-accent">Use-case tiers, by consequence</p>
              <img src={archTiers} alt="Use-case tiers from internal to prohibited, with more human judgment as consequence rises." className="mt-6 w-full" />
            </div>
          </Window>
        </div>
      </div>
    </section>
  );
}
